/**
 * @file    web_page.h
 * @brief   Embedded single-page UI for the OV3660 + W6300 streaming example.
 *
 * The whole UI is one self-contained string: no external CSS, JS, fonts, or
 * images, because the device is the only server the browser can reach.
 *
 * The TOE and lwIP examples serve this same page. What tells them apart is the
 * badge in the header, filled in from the "stack" field of /api/status - so two
 * boards can sit side by side on one screen and be compared directly.
 *
 * Brand colours live in the :root block below. Change those variables to
 * restyle the page; nothing else hard-codes a colour except the chart, which
 * reads them back out of the computed style.
 *
 * HTML attributes use single quotes so the C string needs no escaping.
 */

#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char HTTP_INDEX_PAGE[] =
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>WIZnet Camera Stream</title>\n"
"<style>\n"
":root{\n"
"  --bg:#ffffff; --panel:#ffffff; --line:#dfe5ec;\n"
"  --text:#101418; --muted:#69737f;\n"
/* Red carries emphasis; the buttons and the chart lines keep their own colours
   so the two boards stay comparable against earlier screenshots. */
"  --accent:#e01b24; --ok:#3ddc84; --stop:#ff5c5c; --warn:#f5a623;\n"
/* Set from the status response: one colour per network stack, so which board
   is which is readable across a room without reading any text. */
"  --stack:#e01b24;\n"
"}\n"
"*{box-sizing:border-box}\n"
"body{margin:0;background:var(--bg);color:var(--text);\n"
"  font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif}\n"

/* --- Header: sized for a screen seen from a few metres away --- */
"header{display:flex;align-items:center;gap:18px;padding:12px 24px;\n"
"  background:var(--panel);border-bottom:3px solid var(--stack)}\n"
"header .logo{height:52px;display:block}\n"
"header .sub{color:var(--muted);font-size:13px}\n"
"header .stackbox{margin-left:auto;display:flex;align-items:center;gap:16px}\n"
"header .tag{padding:6px 30px;border-radius:8px;background:var(--stack);\n"
"  color:#ffffff;font-weight:800;font-size:38px;line-height:1.1;\n"
"  letter-spacing:3px;min-width:200px;text-align:center}\n"
"header .what{color:var(--muted);font-size:13px;max-width:210px;\n"
"  line-height:1.4;text-align:right}\n"

/* Video gets the room; everything else is reference material beside it. */
"main{max-width:1500px;margin:0 auto;padding:16px;display:grid;\n"
"  grid-template-columns:minmax(0,1fr) 250px;gap:16px}\n"
"@media(max-width:960px){main{grid-template-columns:1fr}}\n"
".card{background:var(--panel);border:1px solid var(--line);\n"
"  border-radius:10px;padding:14px;box-shadow:0 1px 3px rgba(16,20,24,.06)}\n"
".wide{grid-column:1/-1}\n"
".card h2{margin:0 0 10px;font-size:12px;text-transform:uppercase;\n"
"  letter-spacing:1.5px;color:var(--muted);font-weight:600}\n"
".card.tight{padding:12px}\n"

/* No flex on .view: a flex item defaults to min-width:auto, so an image whose
   natural width exceeds the column overflows instead of scaling down. */
".view{background:#000;border-radius:8px;overflow:hidden;min-height:240px}\n"
".view img{display:block;width:100%;max-width:100%;height:auto}\n"

/* --- Buttons: solid for the two actions that change state, ghost for the
       rest, so the exhibition screen has one obvious pair of controls. --- */
".btns{display:flex;gap:8px;margin-bottom:12px}\n"
"button{padding:9px 12px;border-radius:7px;cursor:pointer;font-size:13px;\n"
"  font-weight:600;letter-spacing:.5px;transition:background .15s,color .15s}\n"
"button:disabled{opacity:.3;cursor:not-allowed}\n"
".btns button{flex:1;border:0;color:#08121c}\n"
"#start{background:var(--ok)} #stop{background:var(--stop)}\n"
".btns button:not(:disabled):hover{filter:brightness(1.1)}\n"
"button.ghost{background:transparent;border:1px solid var(--line);\n"
"  color:var(--muted);font-size:11px;padding:7px 12px;text-transform:uppercase}\n"
"button.ghost:hover{border-color:var(--accent);color:var(--accent)}\n"

"select{width:100%;padding:8px;border-radius:7px;border:1px solid var(--line);\n"
"  background:var(--bg);color:var(--text);font-size:13px}\n"
"label{display:block;font-size:11px;color:var(--muted);margin:0 0 5px}\n"
"dl{display:grid;grid-template-columns:auto 1fr;gap:7px 10px;margin:12px 0 0;font-size:13px}\n"
"dt{color:var(--muted)}\n"
"dd{margin:0;text-align:right;font-variant-numeric:tabular-nums}\n"
".dot{display:inline-block;width:8px;height:8px;border-radius:50%;\n"
"  margin-right:7px;background:var(--muted);vertical-align:middle}\n"
".dot.live{background:var(--ok);box-shadow:0 0 8px var(--ok)}\n"
"footer{text-align:center;color:var(--muted);font-size:12px;padding:8px 0 24px}\n"

/* --- Charts: frame rate on the left, what it costs the link on the right --- */
".charts{display:grid;grid-template-columns:1fr 1fr;gap:24px}\n"
"@media(max-width:900px){.charts{grid-template-columns:1fr}}\n"
".chead{display:flex;align-items:flex-end;gap:16px;margin-bottom:6px;flex-wrap:wrap}\n"
".chead .big{font-size:40px;font-weight:700;line-height:1;\n"
"  font-variant-numeric:tabular-nums}\n"
".chead .big small{font-size:14px;color:var(--muted);margin-left:8px;font-weight:400}\n"
".chead .stats{display:flex;gap:16px;margin-left:auto;font-size:12px;\n"
"  color:var(--muted)}\n"
".chead .stats b{color:var(--text);font-variant-numeric:tabular-nums}\n"
"canvas{display:block;width:100%;height:180px}\n"
".legend{display:flex;flex-wrap:wrap;gap:20px;margin-top:10px;\n"
"  font-size:13px;color:var(--muted)}\n"
".legend i{display:inline-block;width:10px;height:10px;border-radius:2px;\n"
"  margin-right:7px;vertical-align:middle}\n"
".legend b{color:var(--text);font-variant-numeric:tabular-nums}\n"
"i.vsync{background:var(--warn)} i.read{background:var(--accent)}\n"
"i.send{background:#8e7bef}\n"
".hint{margin:12px 0 0;font-size:13px;color:var(--muted);line-height:1.5}\n"
".hint b{color:var(--accent)}\n"

/* --- Sensor clock: one compact row, it is a tuning aid not the exhibit --- */
".sweep{display:flex;flex-wrap:wrap;gap:14px;align-items:center}\n"
".sweep>div{flex:1;min-width:180px;display:flex;align-items:center;gap:10px}\n"
".sweep label{margin:0;white-space:nowrap;font-size:11px}\n"
".sweep label b{color:var(--accent);font-variant-numeric:tabular-nums}\n"
"input[type=range]{flex:1;min-width:90px;accent-color:var(--accent)}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <img class='logo' src='/logo.png' alt='WIZnet'>\n"
"  <div class='sub'>OV3660 &middot; W6300 Ethernet Video Streaming</div>\n"
"  <div class='stackbox'>\n"
"    <div class='what' id='what'>&nbsp;</div>\n"
"    <div class='tag' id='stack'>&nbsp;</div>\n"
"  </div>\n"
"</header>\n"
"<main>\n"
"  <section class='card'>\n"
"    <h2><span id='dot' class='dot'></span>Live view</h2>\n"
"    <div class='view'><img id='view' src='/stream' alt='camera stream'></div>\n"
"  </section>\n"
"  <section class='card'>\n"
"    <h2>Control</h2>\n"
"    <div class='btns'>\n"
"      <button id='start'>START</button>\n"
"      <button id='stop'>STOP</button>\n"
"    </div>\n"
"    <label for='res'>Resolution</label>\n"
"    <select id='res'>\n"
"      <option value='320x240'>320 x 240</option>\n"
"      <option value='640x480'>640 x 480</option>\n"
"      <option value='800x600'>800 x 600</option>\n"
"      <option value='1024x768'>1024 x 768</option>\n"
"      <option value='1280x720'>1280 x 720</option>\n"
"      <option value='1600x1200'>1600 x 1200</option>\n"
"      <option value='2048x1536'>2048 x 1536</option>\n"
"    </select>\n"
"    <dl>\n"
"      <dt>State</dt><dd id='s-state'>-</dd>\n"
"      <dt>Resolution</dt><dd id='s-res'>-</dd>\n"
"      <dt>Frames</dt><dd id='s-frames'>-</dd>\n"
"      <dt>Dropped</dt><dd id='s-drop'>-</dd>\n"
"    </dl>\n"
"  </section>\n"
"  <section class='card wide'>\n"
"    <h2>Live performance</h2>\n"
"    <div class='charts'>\n"
"      <div>\n"
"        <div class='chead'>\n"
"          <div class='big'><span id='s-fps'>0.0</span><small>fps</small></div>\n"
"          <div class='stats'>\n"
"            <span>min <b id='s-min'>-</b></span>\n"
"            <span>avg <b id='s-avg'>-</b></span>\n"
"            <span>max <b id='s-max'>-</b></span>\n"
"          </div>\n"
"        </div>\n"
"        <canvas id='c-fps'></canvas>\n"
"      </div>\n"
"      <div>\n"
"        <div class='chead'>\n"
"          <div class='big'><span id='s-bw'>0.0</span><small>Mbps</small></div>\n"
"          <div class='stats'>\n"
"            <span>frame <b id='s-kb'>0</b> KB</span>\n"
"            <span>peak <b id='s-bwmax'>-</b></span>\n"
"          </div>\n"
"        </div>\n"
"        <canvas id='c-bw'></canvas>\n"
"      </div>\n"
"    </div>\n"
"    <div class='legend'>\n"
"      <span><i class='vsync'></i>VSYNC wait <b id='s-vsync'>0</b> ms</span>\n"
"      <span><i class='read'></i>Sensor readout <b id='s-read'>0</b> ms</span>\n"
"      <span><i class='send'></i>Network send <b id='s-send'>0</b> ms</span>\n"
"    </div>\n"
"    <p class='hint' id='s-hint'>Start streaming to measure.</p>\n"
"  </section>\n"
"  <section class='card tight wide'>\n"
"    <div class='sweep'>\n"
"      <div>\n"
"        <label for='q'>JPEG quality <b id='v-q'>12</b></label>\n"
"        <input type='range' id='q' min='4' max='63' value='12'>\n"
"      </div>\n"
"      <button id='apply' class='ghost'>Apply</button>\n"
"      <button id='reset' class='ghost'>Default</button>\n"
"      <button id='recover' class='ghost'>Recover</button>\n"
"    </div>\n"
"  </section>\n"
"</main>\n"
"<footer>Served from the device</footer>\n"
"<script>\n"
"var $=function(id){return document.getElementById(id)};\n"
"var css=getComputedStyle(document.documentElement);\n"
"var C=function(n){return css.getPropertyValue(n).trim()};\n"
"var last={};\n"

/* ---- Charts: one sample per status poll, eased so the line glides ----
   Both axes are fixed - 0-30 fps and 0-10 Mbps - so the two boards can be read
   against each other at a glance. An auto-scaling axis would rescale itself per
   board and make the side-by-side comparison meaningless. */
"var MAXP=60;\n"
/* fixed = full-scale value, div = gridline count, chosen so every label on
   both charts lands on a whole number. */
"function mkChart(id,rgb,fixed,div){\n"
"  var c={cv:$(id),rgb:rgb,fixed:fixed,div:div,hist:[],shown:0,target:0};\n"
"  c.cx=c.cv.getContext('2d');\n"
"  return c;\n"
"}\n"
"var chF=mkChart('c-fps','0,184,212',30,3);\n"
"var chB=mkChart('c-bw','142,123,239',10,5);\n"
"var charts=[chF,chB];\n"
"function fit(){\n"
"  var d=window.devicePixelRatio||1;\n"
"  charts.forEach(function(c){\n"
"    var r=c.cv.getBoundingClientRect();\n"
"    c.cv.width=Math.max(1,r.width*d);c.cv.height=Math.max(1,r.height*d);\n"
"    c.cx.setTransform(d,0,0,d,0,0);\n"
"  });\n"
"}\n"
"window.addEventListener('resize',fit);fit();\n"
"function push(c,v){\n"
"  c.target=v;c.hist.push(v);if(c.hist.length>MAXP){c.hist.shift()}\n"
"}\n"
"function draw(c){\n"
"  var cx=c.cx,r=c.cv.getBoundingClientRect(),W=r.width,H=r.height;\n"
"  var L=34,R=W-6,T=10,B=H-14,n=c.hist.length;\n"
"  cx.clearRect(0,0,W,H);\n"
"  var mx=c.fixed,dv=c.div;\n"
"  cx.strokeStyle=C('--line');cx.fillStyle=C('--muted');\n"
"  cx.lineWidth=1;cx.font='10px Segoe UI,sans-serif';\n"
"  for(var g=0;g<=dv;g++){\n"
"    var y=T+(B-T)*g/dv,lv=mx*(1-g/dv);\n"
"    cx.beginPath();cx.moveTo(L,y);cx.lineTo(R,y);cx.stroke();\n"
"    cx.fillText(String(Math.round(lv)),4,y+3);\n"
"  }\n"
"  if(n<2){return}\n"
"  var step=(R-L)/(MAXP-1);\n"
"  var X=function(k){return R-(n-1-k)*step};\n"
"  var Y=function(v){return B-(B-T)*Math.min(v,mx)/mx};\n"
"  var path=function(){\n"
"    cx.beginPath();cx.moveTo(X(0),Y(c.hist[0]));\n"
"    for(var k=0;k<n-1;k++){\n"
"      var xc=(X(k)+X(k+1))/2,yc=(Y(c.hist[k])+Y(c.hist[k+1]))/2;\n"
"      cx.quadraticCurveTo(X(k),Y(c.hist[k]),xc,yc);\n"
"    }\n"
"    cx.lineTo(X(n-1),Y(c.hist[n-1]));\n"
"  };\n"
"  var gr=cx.createLinearGradient(0,T,0,B);\n"
"  gr.addColorStop(0,'rgba('+c.rgb+',.34)');\n"
"  gr.addColorStop(1,'rgba('+c.rgb+',0)');\n"
"  path();cx.lineTo(X(n-1),B);cx.lineTo(X(0),B);cx.closePath();\n"
"  cx.fillStyle=gr;cx.fill();\n"
"  path();cx.strokeStyle='rgb('+c.rgb+')';cx.lineWidth=2.5;\n"
"  cx.lineJoin='round';cx.stroke();\n"
"  cx.beginPath();cx.arc(X(n-1),Y(c.hist[n-1]),4,0,6.2832);\n"
"  cx.fillStyle='rgb('+c.rgb+')';cx.fill();\n"
"}\n"
"function tick(){\n"
"  charts.forEach(function(c){\n"
"    c.shown+=(c.target-c.shown)*0.12;\n"
"    if(c.hist.length){c.hist[c.hist.length-1]=c.shown}\n"
"    draw(c);\n"
"  });\n"
"  $('s-fps').textContent=chF.shown.toFixed(1);\n"
"  $('s-bw').textContent=chB.shown.toFixed(1);\n"
"  requestAnimationFrame(tick);\n"
"}\n"
"requestAnimationFrame(tick);\n"

/* ---- Status ---- */
"function call(p){return fetch(p).then(function(r){return r.json()}).then(render)}\n"
"function render(s){\n"
"  $('s-state').textContent=s.streaming?'STREAMING':'STOPPED';\n"
"  $('s-res').textContent=s.res;\n"
"  $('s-frames').textContent=s.frames;\n"
"  $('s-drop').textContent=s.dropped;\n"
"  $('dot').className='dot'+(s.streaming?' live':'');\n"
"  $('start').disabled=s.streaming;\n"
"  $('stop').disabled=!s.streaming;\n"
"  if($('res').value!==s.res){$('res').value=s.res}\n"
"  $('s-kb').textContent=s.kb;\n"
"  $('s-vsync').textContent=s.vsync_ms;\n"
"  $('s-read').textContent=s.read_ms;\n"
"  $('s-send').textContent=s.send_ms;\n"
"  push(chF,s.fps);\n"
/* What the stream actually costs the link: frames per second times the size
   of a frame. KB is already an average over the same window. */
"  push(chB,s.fps*s.kb*8/1000);\n"
"  var mn=1e9,mx=0,sum=0,bmx=0,i,v;\n"
"  for(i=0;i<chF.hist.length;i++){v=chF.hist[i];\n"
"    if(v<mn){mn=v}if(v>mx){mx=v}sum+=v}\n"
"  for(i=0;i<chB.hist.length;i++){if(chB.hist[i]>bmx){bmx=chB.hist[i]}}\n"
"  if(chF.hist.length){\n"
"    $('s-min').textContent=mn.toFixed(1);\n"
"    $('s-max').textContent=mx.toFixed(1);\n"
"    $('s-avg').textContent=(sum/chF.hist.length).toFixed(1);\n"
"    $('s-bwmax').textContent=bmx.toFixed(1)+' Mbps';\n"
"  }\n"
"  $('s-hint').innerHTML=hint(s);\n"
"  if(s.stack){\n"
"    var toe=(s.stack==='TOE');\n"
"    $('stack').textContent=toe?'TOE':'lwIP';\n"
"    $('what').textContent=toe\n"
"      ?'Hardwired TCP/IP - the WIZnet chip terminates TCP'\n"
"      :'Software TCP/IP - lwIP terminates TCP on the MCU';\n"
"    document.documentElement.style.setProperty('--stack',\n"
"      toe?'#e01b24':'#1f2933');\n"
"    document.title=s.stack+' camera';\n"
"  }\n"
"  if(document.activeElement!==$('q')){\n"
"    $('q').value=s.quality;$('v-q').textContent=s.quality;\n"
"  }\n"
"  last=s;\n"
"}\n"
"function hint(s){\n"
"  if(!s.streaming){return 'Start streaming to measure.'}\n"
"  var t=s.vsync_ms+s.read_ms+s.send_ms;if(t<1){t=1}\n"
"  if(s.vsync_ms>=s.read_ms&&s.vsync_ms>=s.send_ms){\n"
"    return 'Bottleneck: <b>VSYNC wait</b>. The device finishes early and idles'+\n"
"      ' until the sensor starts the next frame, so the rate is quantised by'+\n"
"      ' the sensor mode.'}\n"
"  if(s.read_ms>=s.send_ms){\n"
"    return 'Bottleneck: <b>sensor readout</b>. Pixel data takes the longest to'+\n"
"      ' pull out; a coarser JPEG quality below is the lever.'}\n"
"  return 'Bottleneck: <b>network send</b>. Pushing the JPEG out takes the'+\n"
"    ' longest - this is where a hardwired stack and a software stack differ.';\n"
"}\n"

/* ---- Controls ---- */
"var seq=0;\n"
"function restartStream(){$('view').src='/stream?'+(++seq)}\n"
"$('start').onclick=function(){call('/api/start')};\n"
"$('stop').onclick=function(){call('/api/stop')};\n"
"$('res').onchange=function(){\n"
"  var v=this.value;\n"
"  charts.forEach(function(c){c.hist=[];c.shown=0;c.target=0});\n"
"  call('/api/res?v='+v).then(function(){setTimeout(restartStream,300)})\n"
"};\n"
"$('q').oninput=function(){$('v-q').textContent=this.value};\n"
"function applyQuality(v){\n"
"  $('q').value=v;$('v-q').textContent=v;\n"
"  charts.forEach(function(c){c.hist=[];c.shown=0;c.target=0});\n"
"  return call('/api/quality?v='+v);\n"
"}\n"
"$('apply').onclick=function(){applyQuality($('q').value)};\n"
"$('reset').onclick=function(){applyQuality(12)};\n"
"$('recover').onclick=function(){\n"
"  $('recover').textContent='...';\n"
"  call('/api/reset').then(function(){$('recover').textContent='Recover'})\n"
"};\n"
"setInterval(function(){call('/api/status').catch(function(){})},1000);\n"
"call('/api/status').catch(function(){});\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* WEB_PAGE_H */
